-- Create project_activities table
create table if not exists public.project_activities (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_name text,
  action text,
  type text, -- 'figma', 'code', 'image', 'check', 'other'
  details text, -- filename or extra info
  is_active boolean default false,
  project_id uuid references auth.users(id) -- optional link to client
);

-- Enable Row Level Security
alter table public.project_activities enable row level security;

-- Policies
create policy "Enable read access for all users"
on public.project_activities for select
using (true);

create policy "Enable insert for authenticated users"
on public.project_activities for insert
with check (auth.role() = 'authenticated');

-- Insert some dummy data for initial view (REAL Data intent)
insert into public.project_activities (user_name, action, type, details, is_active)
values 
('Selin Y.', 'Homepage_V2.fig tasarımını güncelledi', 'figma', 'Homepage_V2.fig', true),
('Ahmet K.', 'API entegrasyonu tamamlandı', 'code', 'api/client.ts', false),
('Mehmet A.', 'Yeni görseller yüklendi', 'image', 'hero-bg.jpg', false),
('Sistem', 'Deploy işlemi başarılı', 'check', 'v1.0.4', false);
